# Generated by Django 3.2.9 on 2021-12-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211207_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ENLACE',
            field=models.URLField(blank=True, null=True, verbose_name='URL del Sitio'),
        ),
    ]
